### ISSUE TITLE
[cog] implement @santa stats [me|@user|global]

### ISSUE THREAD

**Issue by RalphORama** [Podcast-About-List/santa#16]
## Description of the New Feature

Replacing the `@santa my` and `@santa global` commands is the `@santa stats` command.

## Added Functionality

This feature changes or adds functionality to: report various statistics about gift-giving through the bot. Ideally I'd like these wrapped in an [**Embed**](https://discordpy.readthedocs.io/en/latest/api.html#embed) to give them some snazz.

Commands would function as follows:

- `@santa stats`: prints a message asking for `me`, a `@mention`, or `global`
- `@santa stats me`: displays the following statistics for a user:
    - Current present count
    - Stolen present count
    - Gifted present count
    - Grinch visit count
    - Max owned presents at any time (already stored as `max_present_count` in `santabot/db/models/user.py`
    - *Possibly more - leave your ideas in the comments*

## Affected Components

   - [x] The Discord Bot
   - [x] The Database or API
   - [ ] Other program functionality (`.env`, scripts, etc.)
   - [ ] Documentation
   - [ ] Containerization
   - [ ] CI
   - [ ] Other: 

## New/Additional Dependencies

   - [x] My feature request **does not** add any external dependencies

**Comment by theelk801** [comment]
I'm on this

**Comment by RalphORama** [comment]
This functionality is fully implemented, closing this issue.
