### ISSUE TITLE
Implement Command Cogs

### ISSUE THREAD

**Issue by RalphORama** [Podcast-About-List/santa#4]
The following command cogs need implementation:

   - [ ] `global.py` (depends on #2)
   - [ ] `help.py` (good first cog)
   - [x] `invite.py` (good first cog)
   - [ ] `my.py` (depends on #2)

See `docs/DESIGN.md` for more information involving command implementation if you would like to help.

**Comment by theelk801** [comment]
I'll take `invite.py` I guess

**Comment by RalphORama** [comment]
`invite.py` finished with e96f87d

**Comment by Kameron-Heyen** [comment]
I'll work on `help.py`.

**Comment by Kameron-Heyen** [comment]
I found that help is a reserved word command that already built in and grabs the text from the docstrings. We can disable it and make our own still but I'm curious if you think that this is necessary? This seems to satisfy the requirement unless we want to exclude some admin commands or something.
![Capture](https://user-images.githubusercontent.com/35603228/101858444-3abe8c00-3b2f-11eb-9cb9-9ecf22cbbe5b.PNG)

**Comment by RalphORama** [comment]
I was thinking of using custom embeds or setting up GitHub Pages and responding to a url with a nicely formatted site, but this is perfect for now.

If you don't mind, could you do the following?

- Update docstrings to make more sense for end users
- Hide the `grinch` commands from `help`

**Comment by RalphORama** [comment]
Splitting this into separate issues
